#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : djvulibre
Version  : 1
Release  : 1
URL      : https://github.com/barak/djvulibre/archive/master.zip
Source0  : https://github.com/barak/djvulibre/archive/master.zip
Summary  : DjVu viewers, encoders and utilities.
Group    : Development/Tools
License  : GPL-2.0 zlib-acknowledgement
Requires: djvulibre-bin = %{version}-%{release}
Requires: djvulibre-data = %{version}-%{release}
Requires: djvulibre-lib = %{version}-%{release}
Requires: djvulibre-man = %{version}-%{release}
BuildRequires : autogen
BuildRequires : autogen-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : findutils
BuildRequires : libjpeg-turbo-dev
BuildRequires : libjpeg-turbo-staticdev
BuildRequires : pkgconfig(libtiff-4)
BuildRequires : pkgconfig(libturbojpeg)
BuildRequires : sed
BuildRequires : tiff-dev
BuildRequires : tiff-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
1- WHAT IS DJVU.
================
DjVu (pronounced "déjà vu") a set of compression technologies, a file format,
and a software platform for the delivery over the Web of digital documents,
scanned documents, and high resolution images.

%package bin
Summary: bin components for the djvulibre package.
Group: Binaries
Requires: djvulibre-data = %{version}-%{release}

%description bin
bin components for the djvulibre package.


%package data
Summary: data components for the djvulibre package.
Group: Data

%description data
data components for the djvulibre package.


%package dev
Summary: dev components for the djvulibre package.
Group: Development
Requires: djvulibre-lib = %{version}-%{release}
Requires: djvulibre-bin = %{version}-%{release}
Requires: djvulibre-data = %{version}-%{release}
Provides: djvulibre-devel = %{version}-%{release}
Requires: djvulibre = %{version}-%{release}

%description dev
dev components for the djvulibre package.


%package lib
Summary: lib components for the djvulibre package.
Group: Libraries
Requires: djvulibre-data = %{version}-%{release}

%description lib
lib components for the djvulibre package.


%package man
Summary: man components for the djvulibre package.
Group: Default

%description man
man components for the djvulibre package.


%package staticdev
Summary: staticdev components for the djvulibre package.
Group: Default
Requires: djvulibre-dev = %{version}-%{release}

%description staticdev
staticdev components for the djvulibre package.


%prep
%setup -q -n djvulibre-master
cd %{_builddir}/djvulibre-master

%build
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1598129490
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export CXXFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe"
#
export FCFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
export FFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
export CFFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
#
export LDFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#export CCACHE_DISABLE=1
## altflags1 end
%autogen  --enable-static --enable-shared --enable-desktopfiles=yes
make  %{?_smp_mflags}


%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1598129490
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/any2djvu
/usr/bin/bzz
/usr/bin/c44
/usr/bin/cjb2
/usr/bin/cpaldjvu
/usr/bin/csepdjvu
/usr/bin/ddjvu
/usr/bin/djvm
/usr/bin/djvmcvt
/usr/bin/djvudigital
/usr/bin/djvudump
/usr/bin/djvuextract
/usr/bin/djvumake
/usr/bin/djvups
/usr/bin/djvused
/usr/bin/djvuserve
/usr/bin/djvutoxml
/usr/bin/djvutxt
/usr/bin/djvuxmlparser

%files data
%defattr(-,root,root,-)
/usr/share/djvu/osi/cs/messages.xml
/usr/share/djvu/osi/de/libdjvu++.xml
/usr/share/djvu/osi/de/messages.xml
/usr/share/djvu/osi/en/djvutools-reference.xml
/usr/share/djvu/osi/en/libdjvu++.xml
/usr/share/djvu/osi/en/messages.xml
/usr/share/djvu/osi/fr/libdjvu++.xml
/usr/share/djvu/osi/fr/messages.xml
/usr/share/djvu/osi/ja/libdjvu++.xml
/usr/share/djvu/osi/ja/messages.xml
/usr/share/djvu/osi/languages.xml
/usr/share/djvu/osi/zh/libdjvu++.xml
/usr/share/djvu/osi/zh/messages.xml
/usr/share/djvu/pubtext/DjVuMessages.dtd
/usr/share/djvu/pubtext/DjVuOCR.dtd
/usr/share/djvu/pubtext/DjVuXML-s.dtd
/usr/share/icons/hicolor/128x128/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/16x16/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/20x20/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/22x22/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/24x24/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/256x256/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/32x32/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/48x48/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/64x64/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/72x72/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/96x96/mimetypes/image-vnd.djvu.png
/usr/share/icons/hicolor/scalable/mimetypes/image-vnd.djvu.svgz

%files dev
%defattr(-,root,root,-)
/usr/include/libdjvu/ddjvuapi.h
/usr/include/libdjvu/miniexp.h
/usr/lib64/libdjvulibre.so
/usr/lib64/pkgconfig/ddjvuapi.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdjvulibre.so.21
/usr/lib64/libdjvulibre.so.21.6.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/any2djvu.1
/usr/share/man/man1/bzz.1
/usr/share/man/man1/c44.1
/usr/share/man/man1/cjb2.1
/usr/share/man/man1/cpaldjvu.1
/usr/share/man/man1/csepdjvu.1
/usr/share/man/man1/ddjvu.1
/usr/share/man/man1/djvm.1
/usr/share/man/man1/djvmcvt.1
/usr/share/man/man1/djvu.1
/usr/share/man/man1/djvudigital.1
/usr/share/man/man1/djvudump.1
/usr/share/man/man1/djvuextract.1
/usr/share/man/man1/djvumake.1
/usr/share/man/man1/djvups.1
/usr/share/man/man1/djvused.1
/usr/share/man/man1/djvuserve.1
/usr/share/man/man1/djvutoxml.1
/usr/share/man/man1/djvutxt.1
/usr/share/man/man1/djvuxml.1
/usr/share/man/man1/djvuxmlparser.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libdjvulibre.a
